version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: bookstore_db
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
